### ISSUE TITLE
implicit declaration of function 'esp_a2d_register_data_callback'

### ISSUE THREAD

**Issue by kryvosheiaivan** [h-nari/ESP32_bt_speaker#1]
Hello!
I am going to try your project but i faced with this error:

implicit declaration of function 'esp_a2d_register_data_callback'
Function is located in main.c.
It looks like the deprecated libraries...
Could you help me?

**Comment by h-nari** [comment]
I updated the program. 
Please try it.

**Comment by kryvosheiaivan** [comment]
Thank you for your response!
Old error has disappered! That`s great!
But another exists. It tells that CONFIG_I2S_BCK_PIN, CONFIG_I2S_LRCK_PIN, CONFIG_I2S_DATA_PIN
are undeclared. I think that problems much easier to solve.
Do you know hot to do that?

**Comment by kryvosheiaivan** [comment]
Do you use internal DAC in the project?

**Comment by h-nari** [comment]
Yes．I use internal DAC.

select "Internal DAC"  in your configuration.

**Comment by abhishekaryan013** [comment]
Hey @h-nari  , How to select Internal DAC ?
we need to do in make menuconfig ?
